/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-30 14:12:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/Resources/error.css", Long.valueOf(1675081478898L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>");
      out.write("@charset \"UTF-8\";\n");
      out.write("\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Dosis:300,400,500');\n");
      out.write("\n");
      out.write("@-moz-keyframes rocket-movement { 100% {-moz-transform: translate(1200px,-600px);} }\n");
      out.write("@-webkit-keyframes rocket-movement {100% {-webkit-transform: translate(1200px,-600px); } }\n");
      out.write("@keyframes rocket-movement { 100% {transform: translate(1200px,-600px);} }\n");
      out.write("@-moz-keyframes spin-earth { 100% { -moz-transform: rotate(-360deg); transition: transform 20s;  } }\n");
      out.write("@-webkit-keyframes spin-earth { 100% { -webkit-transform: rotate(-360deg); transition: transform 20s;  } }\n");
      out.write("@keyframes spin-earth{ 100% { -webkit-transform: rotate(-360deg); transform:rotate(-360deg); transition: transform 20s; } }\n");
      out.write("\n");
      out.write("@-moz-keyframes move-astronaut {\n");
      out.write("    100% { -moz-transform: translate(-160px, -160px);}\n");
      out.write("}\n");
      out.write("@-webkit-keyframes move-astronaut {\n");
      out.write("    100% { -webkit-transform: translate(-160px, -160px);}\n");
      out.write("}\n");
      out.write("@keyframes move-astronaut{\n");
      out.write("    100% { -webkit-transform: translate(-160px, -160px); transform:translate(-160px, -160px); }\n");
      out.write("}\n");
      out.write("@-moz-keyframes rotate-astronaut {\n");
      out.write("    100% { -moz-transform: rotate(-720deg);}\n");
      out.write("}\n");
      out.write("@-webkit-keyframes rotate-astronaut {\n");
      out.write("    100% { -webkit-transform: rotate(-720deg);}\n");
      out.write("}\n");
      out.write("@keyframes rotate-astronaut{\n");
      out.write("    100% { -webkit-transform: rotate(-720deg); transform:rotate(-720deg); }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@-moz-keyframes glow-star {\n");
      out.write("    40% { -moz-opacity: 0.3;}\n");
      out.write("    90%,100% { -moz-opacity: 1; -moz-transform: scale(1.2);}\n");
      out.write("}\n");
      out.write("@-webkit-keyframes glow-star {\n");
      out.write("    40% { -webkit-opacity: 0.3;}\n");
      out.write("    90%,100% { -webkit-opacity: 1; -webkit-transform: scale(1.2);}\n");
      out.write("}\n");
      out.write("@keyframes glow-star{\n");
      out.write("    40% { -webkit-opacity: 0.3; opacity: 0.3;  }\n");
      out.write("    90%,100% { -webkit-opacity: 1; opacity: 1; -webkit-transform: scale(1.2); transform: scale(1.2); border-radius: 999999px;}\n");
      out.write("}\n");
      out.write("\n");
      out.write(".spin-earth-on-hover{\n");
      out.write("    \n");
      out.write("    transition: ease 200s !important;\n");
      out.write("    transform: rotate(-3600deg) !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write("html, body{\n");
      out.write("    margin: 0;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("    font-family: 'Dosis', sans-serif;\n");
      out.write("    font-weight: 300;\n");
      out.write("    -webkit-user-select: none; /* Safari 3.1+ */\n");
      out.write("    -moz-user-select: none; /* Firefox 2+ */\n");
      out.write("    -ms-user-select: none; /* IE 10+ */\n");
      out.write("    user-select: none; /* Standard syntax */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bg-purple{\n");
      out.write("    background: url(http://salehriaz.com/404Page/img/bg_purple.png);\n");
      out.write("    background-repeat: repeat-x;\n");
      out.write("    background-size: cover;\n");
      out.write("    background-position: left top;\n");
      out.write("    height: 100%;\n");
      out.write("    overflow: hidden;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".custom-navbar{\n");
      out.write("    padding-top: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".brand-logo{\n");
      out.write("    margin-left: 25px;\n");
      out.write("    margin-top: 5px;\n");
      out.write("    display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navbar-links{\n");
      out.write("    display: inline-block;\n");
      out.write("    float: right;\n");
      out.write("    margin-right: 15px;\n");
      out.write("    text-transform: uppercase;\n");
      out.write("    \n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write("ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("/*    overflow: hidden;*/\n");
      out.write("    display: flex; \n");
      out.write("    align-items: center; \n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("    float: left;\n");
      out.write("    padding: 0px 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a {\n");
      out.write("    display: block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    text-decoration: none;\n");
      out.write("    letter-spacing : 2px;\n");
      out.write("    font-size: 12px;\n");
      out.write("    \n");
      out.write("    -webkit-transition: all 0.3s ease-in;\n");
      out.write("    -moz-transition: all 0.3s ease-in;\n");
      out.write("    -ms-transition: all 0.3s ease-in;\n");
      out.write("    -o-transition: all 0.3s ease-in;\n");
      out.write("    transition: all 0.3s ease-in;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover {\n");
      out.write("    color: #ffcb39;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-request{\n");
      out.write("    padding: 10px 25px;\n");
      out.write("    border: 1px solid #FFCB39;\n");
      out.write("    border-radius: 100px;\n");
      out.write("    font-weight: 400;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-request:hover{\n");
      out.write("    background-color: #FFCB39;\n");
      out.write("    color: #fff;\n");
      out.write("    transform: scale(1.05);\n");
      out.write("    box-shadow: 0px 20px 20px rgba(0,0,0,0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-go-home{\n");
      out.write("    position: relative;\n");
      out.write("    z-index: 200;\n");
      out.write("    margin: 15px auto;\n");
      out.write("    width: 100px;\n");
      out.write("    padding: 10px 15px;\n");
      out.write("    border: 1px solid #FFCB39;\n");
      out.write("    border-radius: 100px;\n");
      out.write("    font-weight: 400;\n");
      out.write("    display: block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    text-decoration: none;\n");
      out.write("    letter-spacing : 2px;\n");
      out.write("    font-size: 11px;\n");
      out.write("    \n");
      out.write("    -webkit-transition: all 0.3s ease-in;\n");
      out.write("    -moz-transition: all 0.3s ease-in;\n");
      out.write("    -ms-transition: all 0.3s ease-in;\n");
      out.write("    -o-transition: all 0.3s ease-in;\n");
      out.write("    transition: all 0.3s ease-in;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-go-home:hover{\n");
      out.write("    background-color: #FFCB39;\n");
      out.write("    color: #fff;\n");
      out.write("    transform: scale(1.05);\n");
      out.write("    box-shadow: 0px 20px 20px rgba(0,0,0,0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".central-body{\n");
      out.write("/*    width: 100%;*/\n");
      out.write("    padding: 17% 5% 10% 5%;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".objects img{\n");
      out.write("    z-index: 90;\n");
      out.write("    pointer-events: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".object_rocket{\n");
      out.write("    z-index: 95;\n");
      out.write("    position: absolute;\n");
      out.write("    transform: translateX(-50px);\n");
      out.write("    top: 75%;\n");
      out.write("    pointer-events: none;\n");
      out.write("    animation: rocket-movement 200s linear infinite both running;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".object_earth{\n");
      out.write("    position: absolute;\n");
      out.write("    top: 20%;\n");
      out.write("    left: 15%;\n");
      out.write("    z-index: 90;\n");
      out.write("/*    animation: spin-earth 100s infinite linear both;*/\n");
      out.write("}\n");
      out.write("\n");
      out.write(".object_moon{\n");
      out.write("    position: absolute;\n");
      out.write("    top: 12%;\n");
      out.write("    left: 25%;\n");
      out.write("/*\n");
      out.write("    transform: rotate(0deg);\n");
      out.write("    transition: transform ease-in 99999999999s;\n");
      out.write("*/\n");
      out.write("}\n");
      out.write("\n");
      out.write(".earth-moon{\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".object_astronaut{\n");
      out.write("    animation: rotate-astronaut 200s infinite linear both alternate;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".box_astronaut{\n");
      out.write("    z-index: 110 !important;\n");
      out.write("    position: absolute;\n");
      out.write("    top: 60%;\n");
      out.write("    right: 20%;\n");
      out.write("    will-change: transform;\n");
      out.write("    animation: move-astronaut 50s infinite linear both alternate;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".image-404{\n");
      out.write("    position: relative;\n");
      out.write("    z-index: 100;\n");
      out.write("    pointer-events: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".stars{\n");
      out.write("    background: url(http://salehriaz.com/404Page/img/overlay_stars.svg);\n");
      out.write("    background-repeat: repeat;\n");
      out.write("    background-size: contain;\n");
      out.write("    background-position: left top;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".glowing_stars .star{\n");
      out.write("    position: absolute;\n");
      out.write("    border-radius: 100%;\n");
      out.write("    background-color: #fff;\n");
      out.write("    width: 3px;\n");
      out.write("    height: 3px;\n");
      out.write("    opacity: 0.3;\n");
      out.write("    will-change: opacity;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".glowing_stars .star:nth-child(1){\n");
      out.write("    top: 80%;\n");
      out.write("    left: 25%;\n");
      out.write("    animation: glow-star 2s infinite ease-in-out alternate 1s;\n");
      out.write("}\n");
      out.write(".glowing_stars .star:nth-child(2){\n");
      out.write("    top: 20%;\n");
      out.write("    left: 40%;\n");
      out.write("    animation: glow-star 2s infinite ease-in-out alternate 3s;\n");
      out.write("}\n");
      out.write(".glowing_stars .star:nth-child(3){\n");
      out.write("    top: 25%;\n");
      out.write("    left: 25%;\n");
      out.write("    animation: glow-star 2s infinite ease-in-out alternate 5s;\n");
      out.write("}\n");
      out.write(".glowing_stars .star:nth-child(4){\n");
      out.write("    top: 75%;\n");
      out.write("    left: 80%;\n");
      out.write("    animation: glow-star 2s infinite ease-in-out alternate 7s;\n");
      out.write("}\n");
      out.write(".glowing_stars .star:nth-child(5){\n");
      out.write("    top: 90%;\n");
      out.write("    left: 50%;\n");
      out.write("    animation: glow-star 2s infinite ease-in-out alternate 9s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media only screen and (max-width: 600px){\n");
      out.write("    .navbar-links{\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .custom-navbar{\n");
      out.write("        text-align: center;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .brand-logo img{\n");
      out.write("        width: 120px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .box_astronaut{\n");
      out.write("        top: 70%;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .central-body{\n");
      out.write("        padding-top: 25%;\n");
      out.write("    }\n");
      out.write("}");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"bg-purple\">\n");
      out.write("        \n");
      out.write("        <div class=\"stars\">\n");
      out.write("            <div class=\"custom-navbar\">\n");
      out.write("                <div class=\"brand-logo\">\n");
      out.write("                    <img src=\"http://salehriaz.com/404Page/img/logo.svg\" width=\"80px\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"navbar-links\">\n");
      out.write("                    <ul>\n");
      out.write("                      <li><a href=\"http://salehriaz.com/404Page/404.html\" target=\"_blank\">Home</a></li>\n");
      out.write("                      <li><a href=\"http://salehriaz.com/404Page/404.html\" target=\"_blank\">About</a></li>\n");
      out.write("                      <li><a href=\"http://salehriaz.com/404Page/404.html\" target=\"_blank\">Features</a></li>\n");
      out.write("                      <li><a href=\"http://salehriaz.com/404Page/404.html\" class=\"btn-request\" target=\"_blank\">Request A Demo</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"central-body\">\n");
      out.write("                <img class=\"image-404\" src=\"http://salehriaz.com/404Page/img/404.svg\" width=\"300px\">\n");
      out.write("                <a href=\"http://salehriaz.com/404Page/404.html\" class=\"btn-go-home\" target=\"_blank\">GO BACK HOME</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"objects\">\n");
      out.write("                <img class=\"object_rocket\" src=\"http://salehriaz.com/404Page/img/rocket.svg\" width=\"40px\">\n");
      out.write("                <div class=\"earth-moon\">\n");
      out.write("                    <img class=\"object_earth\" src=\"http://salehriaz.com/404Page/img/earth.svg\" width=\"100px\">\n");
      out.write("                    <img class=\"object_moon\" src=\"http://salehriaz.com/404Page/img/moon.svg\" width=\"80px\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"box_astronaut\">\n");
      out.write("                    <img class=\"object_astronaut\" src=\"http://salehriaz.com/404Page/img/astronaut.svg\" width=\"140px\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"glowing_stars\">\n");
      out.write("                <div class=\"star\"></div>\n");
      out.write("                <div class=\"star\"></div>\n");
      out.write("                <div class=\"star\"></div>\n");
      out.write("                <div class=\"star\"></div>\n");
      out.write("                <div class=\"star\"></div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
